<?$GLOBALS['arTopMenuBrandsFilter'] = [
  '!PROPERTY_SHOW_TOP_MENU_VALUE' => false,
];?>
<?$APPLICATION->IncludeComponent(
  "bitrix:news.list",
  "brands-list",
  array(
    "IBLOCK_ID" => TSolution\Cache::getStaticIBlockID('content', 'brands', SITE_ID),
    "NEWS_COUNT" => "20",
    "SORT_BY1" => "SORT",
    "SORT_ORDER1" => "DESC",
    "SORT_BY2" => "SORT",
    "SORT_ORDER2" => "ASC",
    "FILTER_NAME" => "arTopMenuBrandsFilter",
    "FIELD_CODE" => array(
      "PREVIEW_PICTURE",
    ),
    "PROPERTY_CODE" => array(
      "SHOW_TOP_MENU",
    ),
    "CHECK_DATES" => "Y",
    "DETAIL_URL" => "",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "AJAX_OPTION_HISTORY" => "N",
    "CACHE_TYPE" => "A",
    "CACHE_TIME" => "36000000",
    "CACHE_FILTER" => "Y",
    "CACHE_GROUPS" => "N",
    "PREVIEW_TRUNCATE_LEN" => "",
    "ACTIVE_DATE_FORMAT" => "d.m.Y",
    "SET_TITLE" => "N",
    "SET_STATUS_404" => "N",
    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
    "ADD_SECTIONS_CHAIN" => "N",
    "HIDE_LINK_WHEN_NO_DETAIL" => "N",
    "PARENT_SECTION" => "",
    "PARENT_SECTION_CODE" => "",
    "DISPLAY_TOP_PAGER" => "N",
    "DISPLAY_BOTTOM_PAGER" => "N",
    "PAGER_TITLE" => "",
    "PAGER_SHOW_ALWAYS" => "N",
    "PAGER_TEMPLATE" => "ajax",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "3600",
    "PAGER_SHOW_ALL" => "N",
    "DISPLAY_DATE" => "Y",
    "DISPLAY_NAME" => "Y",
    "DISPLAY_PICTURE" => "N",
    "DISPLAY_PREVIEW_TEXT" => "N",
    "AJAX_OPTION_ADDITIONAL" => "",
    "COMPONENT_TEMPLATE" => "brands-list",
    "SET_BROWSER_TITLE" => "N",
    "SET_META_KEYWORDS" => "N",
    "SET_META_DESCRIPTION" => "N",
    "SET_LAST_MODIFIED" => "N",
    "INCLUDE_SUBSECTIONS" => "Y",
    "STRICT_SECTION_CHECK" => "N",
    "PAGER_BASE_LINK_ENABLE" => "N",
    "SHOW_404" => "N",
    "COMPOSITE_FRAME_MODE" => "A",
    "COMPOSITE_FRAME_TYPE" => "AUTO",
    "BORDERED" => "N",
    "FON" => "Y",
    "SLIDER" => "N",
    "SHOW_PREVIEW_TEXT" => "Y",
    "MAXWIDTH_WRAP" => "N",
    "IS_TOP_MENU" => true,
    "HIDE_ICONS" => "Y",
  ),
  false,
  [
    'HIDE_ICONS' => 'Y',
  ]
);
