<?if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) {
    exit;
}?>
<?$APPLICATION->IncludeComponent(
    'bitrix:catalog.section',
    'catalog_list',
    [
        'CACHE_TYPE' => $arParams['CACHE_TYPE'],
        'CACHE_TIME' => $arParams['CACHE_TIME'],
        'CACHE_FILTER' => $arParams['CACHE_FILTER'],
        'CACHE_GROUPS' => $arParams['CACHE_GROUPS'],
        'DETAIL_URL' => $arResult['FOLDER'].$arResult['URL_TEMPLATES']['element'],
        'FILTER_NAME' => $arParams['FILTER_NAME'],
        'HIT_PROP' => 'HIT',
        'IBLOCK_TYPE' => $arParams['IBLOCK_TYPE'],
        'IBLOCK_ID' => $arParams['IBLOCK_ID'],

        'DISPLAY_COMPARE' => $arParams['DISPLAY_COMPARE'],
        'SHOW_FAVORITE' => $arParams['SHOW_FAVORITE'],

        'SKU_IBLOCK_ID' => $arParams['SKU_IBLOCK_ID'],
        'SKU_TREE_PROPS' => $arParams['SKU_TREE_PROPS'],
        'SKU_PROPERTY_CODE' => $arParams['SKU_PROPERTY_CODE'],
        'OFFERS_SORT_FIELD' => $arParams['SKU_SORT_FIELD'],
        'OFFERS_SORT_ORDER' => $arParams['SKU_SORT_ORDER'],
        'OFFERS_SORT_FIELD2' => $arParams['SKU_SORT_FIELD2'],
        'OFFERS_SORT_ORDER2' => $arParams['SKU_SORT_ORDER2'],

        'OFFER_TREE_PROPS' => $arParams['SKU_TREE_PROPS'],
        'OFFERS_PROPERTY_CODE' => $arParams['SKU_PROPERTY_CODE'],
        'OFFERS_FIELD_CODE' => array_merge(['ID', 'NAME'], (array) $arParams['LIST_OFFERS_FIELD_CODE']),

        'ADD_PROPERTIES_TO_BASKET' => $arParams['ADD_PROPERTIES_TO_BASKET'],
        'PARTIAL_PRODUCT_PROPERTIES' => $arParams['PARTIAL_PRODUCT_PROPERTIES'],
        'PRODUCT_PROPS_VARIABLE' => $arParams['PRODUCT_PROPS_VARIABLE'],
        'PRODUCT_PROPERTIES' => $arParams['PRODUCT_PROPERTIES'],
        'OFFERS_CART_PROPERTIES' => $arParams['OFFERS_CART_PROPERTIES'],

        'USE_PRODUCT_QUANTITY' => $arParams['USE_PRODUCT_QUANTITY'],
        'CONVERT_CURRENCY' => $arParams['CONVERT_CURRENCY'],
        'CURRENCY_ID' => $arParams['CURRENCY_ID'],
        'PRICE_VAT_INCLUDE' => $arParams['PRICE_VAT_INCLUDE'],
        'HIDE_NOT_AVAILABLE' => $arParams['HIDE_NOT_AVAILABLE'],
        'HIDE_NOT_AVAILABLE_OFFERS' => $arParams['HIDE_NOT_AVAILABLE_OFFERS'],
        'SHOW_HINTS' => $arParams['SHOW_HINTS'],
        'PAGE_ELEMENT_COUNT' => $arParams['PAGE_ELEMENT_COUNT'],
        'PROPERTY_CODE' => $arParams['LIST_PROPERTY_CODE'],
        'ELEMENT_SORT_FIELD' => $sectionSort ?? $arAvailableSort[$sortKey]['SORT'],
        'ELEMENT_SORT_ORDER' => $sectionSortOrder ?? strtoupper($order),
        'ELEMENT_SORT_FIELD2' => $arParams['ELEMENT_SORT_FIELD2'],
        'ELEMENT_SORT_ORDER2' => $arParams['ELEMENT_SORT_ORDER2'],
        'SECTION_ID' => $arResult['VARIABLES']['SECTION_ID'],
        'SECTION_CODE' => $arResult['VARIABLES']['SECTION_CODE'],
        'FIELD_CODE' => $arParams['LIST_FIELD_CODE'],
        'ELEMENTS_TABLE_TYPE_VIEW' => 'FROM_MODULE',
        'SHOW_SECTION' => 'Y',
        'COUNT_IN_LINE' => $arParams['LINE_ELEMENT_COUNT'],
        'LINE_ELEMENT_COUNT' => $arParams['LINE_ELEMENT_COUNT'],
        'SHOW_DISCOUNT_TIME' => $arParams['SHOW_DISCOUNT_TIME'],
        'SHOW_OLD_PRICE' => $arParams['SHOW_OLD_PRICE'],
        'DISCOUNT_PRICE' => $arParams['DISCOUNT_PRICE'],
        'SHOW_DISCOUNT_PERCENT' => $arParams['SHOW_DISCOUNT_PERCENT'],
        'SHOW_MEASURE' => $arParams['SHOW_MEASURE'],
        'SHOW_POPUP_PRICE' => $arParams['SHOW_POPUP_PRICE'],
        'PRICE_CODE' => $arParams['PRICE_CODE'],
        'STORES' => $arParams['STORES'],
        'SHOW_GALLERY' => $arParams['SHOW_GALLERY'],
        'ADD_PICT_PROP' => $arParams['ADD_PICT_PROP'],
        'OFFER_ADD_PICT_PROP' => $arParams['OFFER_ADD_PICT_PROP'],
        'MAX_GALLERY_ITEMS' => $arParams['MAX_GALLERY_ITEMS'],
        'DISPLAY_TOP_PAGER' => $arParams['DISPLAY_TOP_PAGER'],
        'DISPLAY_BOTTOM_PAGER' => $arParams['DISPLAY_BOTTOM_PAGER'],
        'PAGER_TITLE' => $arParams['PAGER_TITLE'],
        'PAGER_TEMPLATE' => $arParams['PAGER_TEMPLATE'],
        'PAGER_SHOW_ALWAYS' => $arParams['PAGER_SHOW_ALWAYS'],
        'PAGER_DESC_NUMBERING' => $arParams['PAGER_DESC_NUMBERING'],
        'PAGER_DESC_NUMBERING_CACHE_TIME' => $arParams['PAGER_DESC_NUMBERING_CACHE_TIME'],
        'PAGER_SHOW_ALL' => $arParams['PAGER_SHOW_ALL'],
        'INCLUDE_SUBSECTIONS' => $arParams['INCLUDE_SUBSECTIONS'],
        // "SHOW_ALL_WO_SECTION" => "Y", this param prevents execution of USE_MAIN_ELEMENT_SECTION
        'HEADING_COUNT_ELEMENTS' => $arParams['HEADING_COUNT_ELEMENTS'],
        'IS_CATALOG_PAGE' => ('N' == $arParams['INCLUDE_SUBSECTIONS'] ? '' : 'Y'),
        'META_KEYWORDS' => $arParams['LIST_META_KEYWORDS'],
        'META_DESCRIPTION' => $arParams['LIST_META_DESCRIPTION'],
        'BROWSER_TITLE' => $arParams['LIST_BROWSER_TITLE'],
        'ADD_SECTIONS_CHAIN' => ($iSectionsCount && 'N' == $arParams['INCLUDE_SUBSECTIONS']) ? 'N' : $arParams['ADD_SECTIONS_CHAIN'],
        'MOBILE_SCROLLED' => false,
        'ITEMS_OFFSET' => 'Y',
        'GRID_GAP' => '',
        'AJAX_REQUEST' => $isAjax,
        'SHOW_ONE_CLICK_BUY' => $arParams['SHOW_ONE_CLICK_BUY'],
        'USE_FAST_VIEW_PAGE_DETAIL' => $arParams['USE_FAST_VIEW_PAGE_DETAIL'],
        'EXPRESSION_FOR_FAST_VIEW' => $arParams['EXPRESSION_FOR_FAST_VIEW'],
        'SHOW_RATING' => $arParams['SHOW_RATING'],
        'ORDER_VIEW' => $arParams['ORDER_VIEW'],
        'USE_PRICE_COUNT' => $arParams['USE_PRICE_COUNT'],
        'SHOW_PRICE_COUNT' => $arParams['SHOW_PRICE_COUNT'],
        'USE_REGION' => $arParams['USE_REGION'],
        'TYPE_SKU' => $arParams['TYPE_SKU'],
        'IBINHERIT_TEMPLATES' => $arIBInheritTemplates ?? [],
        'OFFERS_LIMIT' => $arParams['OFFERS_LIMIT'],
        'USE_MAIN_ELEMENT_SECTION' => $arParams['USE_MAIN_ELEMENT_SECTION'],
        'COMPATIBLE_MODE' => $arParams['COMPATIBLE_MODE'] ?? 'Y',
        'SHOW_SKU_DESCRIPTION' => $arParams['SHOW_SKU_DESCRIPTION'],
        'CURRENT_BASE_PAGE' => TSolution\CacheableUrl::get(),
        'PAGER_BASE_LINK' => TSolution\CacheableUrl::get(),
        'PAGER_BASE_LINK_ENABLE' => 'Y',
        "SET_SKU_TITLE" => $arParams['SET_SKU_TITLE'],
    ],
    $component, ['HIDE_ICONS' => $isAjax]
); ?>
